### ISSUE TITLE
Add an option in the config for spawnrate and maybe allowed dimensions?

### ISSUE THREAD

**Issue by SpencerMeow** [gigaherz/EyesInTheDarkness#20]
Eyes seem to spawn quite too much (atleast for my taste) and in every dimension so it would be really cool if we had a spawn rate option in the config file.

**Comment by gigaherz** [comment]
Hi, what version are you on? The most recent updates for 1.16.5 have a custom spawning system with such configs.
I don't generally backport features so this will be missing from all older versions.

Due to how the vanilla spawning system works, it wasn't possible to truly adjust the spawn rate at all because vanilla controls the rate, And it wasn't possible to control spawnable dimensions because there's no dimension context when mob spawns are registered. This meant the only solution was a custom spawning system where those values are under my control.

**Comment by SpencerMeow** [comment]
> Hi, what version are you on? The most recent updates for 1.16.5 have a custom spawning system with such configs.
> I don't generally backport features so this will be missing from all older versions.
> 
> Due to how the vanilla spawning system works, it wasn't possible to truly adjust the spawn rate at all because vanilla controls the rate, And it wasn't possible to control spawnable dimensions because there's no dimension context when mob spawns are registered. This meant the only solution was a custom spawning system where those values are under my control.

I'm on version 1.0.2 for 1.16.5. All I see in the config "eyesinthedarkness-client.toml" is

[general]
	#Set to false to prevent jumpscares from displaying client-side.
	#NOTE: Jumpscare effects such as poison still apply, this only prevents the visual and sound.
	jumpscare = true

**Comment by gigaherz** [comment]
You won't find that in the client configs. You have to look at the server configs, located in the world folder, under serverconfigs. If you are making a modpack you can copy the final configs to the "defaultconfigs" up on the instance folder, but I presume if you are making a modpack you'd know that by now... considering all mods work that way.

**Comment by SpencerMeow** [comment]
Oh I didn't even realize you had one in the server configs folder! It seems to be working fine now and...dang that's a lot of config options so thank you!
