### ISSUE TITLE
Shader compat

### ISSUE THREAD

**Issue by Aabaddon** [gigaherz/EyesInTheDarkness#26]
For some reason the eyes are VERY difficult to find with complementary reimagined shaders, they dont glow like every other mob´s eyes

![glowing eyes](https://github.com/gigaherz/EyesInTheDarkness/assets/41172599/8a11b0de-93a0-4dda-8feb-d465222d6bfd)
![eyes](https://github.com/gigaherz/EyesInTheDarkness/assets/41172599/8d1a361f-ce79-49dc-ab86-d3bca8c7e470)

**Comment by gigaherz** [comment]
That's probably because I don't draw them with the "eyes" render type, but rather using standard rendering with fullbright(emissinve) vertex lighting. I probably should change that, not because of shaders, but because it interacts badly with the Darkness effect. The fix for shaders would be a bonus, heh.

What version of mc are you on? Because I would be fixing on 1.20.1 and 1.19.2, but I consider older versions out of support.

**Comment by Aabaddon** [comment]
im playin on 1.20.1 so i think it would be perfect lol, thanks

**Comment by gigaherz** [comment]
Fixed in v1.3.10, which is awaiting approval on curseforge.
